# https://raw.githubusercontent.com/grafana/loki/935aee77ed389c825d36b8d6a85c0d83895a24d1/clients/cmd/promtail/promtail-docker-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https://loki.domain.com/loki/api/v1/push
    basic_auth:
      username: <username>
      password: <password>

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          __path__: /var/lib/docker/containers/*/*-json.log
