{
 "title": "IRISnet",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": "label_values(tendermint_consensus_height, chain_id)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{instance=\"$instance\",job=\"node\",mode='idle'}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Root Disk Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$instance\",job=\"node\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",job=\"node\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$instance\",job=\"node\"} * 100) / node_memory_MemTotal_bytes{instance=\"$instance\",job=\"node\"})"
    }
   ]
  },
  {
   "title": "CPU Load (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\",job=\"node\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Load (5m avg)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$instance\",job=\"node\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\",job=\"node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "Total Root Disk",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",instance=\"$instance\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "System Load (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\",job=\"node\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 5 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\",job=\"node\"} - node_boot_time_seconds{instance=\"$instance\",job=\"node\"}"
    }
   ]
  },
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Block Height",
   "type": "singlestat",
   "description": "Height of the chain",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_height{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Amount Validators",
   "type": "singlestat",
   "description": "Number of validators",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Total Voting Power",
   "type": "singlestat",
   "description": "Total voting power of all validators",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}/1000000"
    }
   ]
  },
  {
   "title": "Missing + Byzantine Validators",
   "type": "singlestat",
   "description": "Percentage of missing + byzantine validators",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 9 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"} + tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}) / tendermint_consensus_validators_power{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}) * 100"
    }
   ]
  },
  {
   "title": "Latest Block",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Byzantine Validators",
   "type": "singlestat",
   "description": "Number of validators who tried to double sign",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Committed Txs",
   "type": "singlestat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Consensus Rounds",
   "type": "singlestat",
   "description": "Number of rounds",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tendermint_consensus_rounds{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Number of Transactions",
   "type": "singlestat",
   "description": "Number of transactions",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Missing Validators Voting Power",
   "type": "singlestat",
   "description": "Total voting power of the missing validators",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}/1000000"
    }
   ]
  },
  {
   "title": "Fast Syncing",
   "type": "singlestat",
   "description": "Number of rounds",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_fast_syncing{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": " Byzantine Validators Voting Power",
   "type": "singlestat",
   "description": "Total voting power of the byzantine validators",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "singlestat",
   "description": "Block size in bytes",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 13 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Validators Missing",
   "type": "singlestat",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Avg Block Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 13 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time(tendermint_consensus_block_interval_seconds{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}[1m])"
    }
   ]
  },
  {
   "title": "Block TIme",
   "type": "graph",
   "description": "Time between this and last block (Block.Header.Time) in seconds\n#\nDoesn't seem to receive any",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  { "title": "Stake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Voting Power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "iris_module_stake_power{instance=\"$instance\",job=\"irishub\", validator_address=\"ica1summn6ymk3us2l50qfemcasr84v44t9cats6s4\"}"
    }
   ]
  },
  {
   "title": "Total Bonded Tokens",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "iris_module_stake_bonded_token{instance=\"$instance\",job=\"irishub\",validator_address=\"ica1summn6ymk3us2l50qfemcasr84v44t9cats6s4\"}"
    }
   ]
  },
  {
   "title": "Upgrade Needed?",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 23 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "iris_module_upgrade_upgrade{instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  { "title": "p2p", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Connected Peers",
   "type": "singlestat",
   "description": "Number of peers node's connected to\n\n(Need to change Threshold)",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Mempool Size",
   "type": "singlestat",
   "description": "Number of uncommitted transactions",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_mempool_size{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Tx Size Bytes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 29 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_mempool_tx_size_bytes_sum{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Recheck Times",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 29 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Voting Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "STEAK" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  },
  {
   "title": "Absent Validators",
   "type": "graph",
   "description": "Number of validators who did not sign",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\",instance=\"$instance\",job=\"irishub\"}"
    }
   ]
  }
 ]
}